### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TRemills** [Keksuccino/Konkrete#3]

**Comment by TRemills** [comment]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2021-07-17 22:23:23 YEKT
Description: Initializing game

java.lang.NoClassDefFoundError: de/keksuccino/konkrete/config/exceptions/InvalidValueException
    at net.minecraft.client.Minecraft.handler$zce000$onGetWindowTitle(Minecraft.java:4835)
    at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java)
    at net.minecraft.client.Minecraft.init(Minecraft.java:545)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: de.keksuccino.konkrete.config.exceptions.InvalidValueException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 11 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 542372872 bytes (517 MB) / 1073741824 bytes (1024 MB) up to 10737418240 bytes (10240 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 77 mods loaded, 77 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                    | Version                  | Source                                                | Signature                                |
       |:----- |:--------------------- |:------------------------ |:----------------------------------------------------- |:---------------------------------------- |
       | L     | minecraft             | 1.12.2                   | minecraft.jar                                         | None                                     |
       | L     | mcp                   | 9.42                     | minecraft.jar                                         | None                                     |
       | L     | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | forge                 | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | additionalresources   | 0.1.1                    | additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar | None                                     |
       | L     | advancedrocketrycore  | 1                        | minecraft.jar                                         | None                                     |
       | L     | creativecoredummy     | 1.0.0                    | minecraft.jar                                         | None                                     |
       | L     | itemphysic            | 1.4.0                    | minecraft.jar                                         | None                                     |
       | L     | fancymenu             | 2.2.0                    | fancymenu_2.2.0-1_MC_1.12-1.12.2.jar                  | None                                     |
       | L     | advancedrocketry      | 2.0.0.-250               | AdvancedRocketry-1.12.2-2.0.0-250-universal.jar       | None                                     |
       | L     | ambientsounds         | 3.0                      | AmbientSounds_v3.1.5_mc1.12.2.jar                     | None                                     |
       | L     | appleskin             | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                           | None                                     |
       | L     | attributefix          | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                         | None                                     |
       | L     | audiodeath            | 0.7.0_1.9-87aeca7        | audiodeath-1.9-0.7.0.50+87aeca7.jar                   | None                                     |
       | L     | autoreglib            | 1.3-32                   | AutoRegLib-1.3-32.jar                                 | None                                     |
       | L     | betteradvancements    | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar                | None                                     |
       | L     | bettercaves           | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                          | None                                     |
       | L     | bettergolem           | 1.0                      | bettergolem-1.12.2-1.0.jar                            | None                                     |
       | L     | bettermineshafts      | 1.12.2-2.2.1             | BetterMineshaftsForge-1.12.2-2.2.1.jar                | None                                     |
       | L     | biomesoplenty         | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar         | None                                     |
       | L     | blur                  | 1.0.4-14                 | Blur-1.0.4-14.jar                                     | None                                     |
       | L     | bountiful             | 2.2.2                    | Bountiful-2.2.2.jar                                   | None                                     |
       | L     | car                   | 2.0.1                    | car-1.12.2-2.0.1.jar                                  | None                                     |
       | L     | colytra               | 1.2.0.4                  | colytra-1.12.2-1.2.0.4.jar                            | None                                     |
       | L     | cosmeticarmorreworked | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar                  | None                                     |
       | L     | ctgui                 | 1.0.0                    | CraftTweaker2-1.12-4.1.20.655.jar                     | None                                     |
       | L     | crafttweaker          | 4.1.20                   | CraftTweaker2-1.12-4.1.20.655.jar                     | None                                     |
       | L     | crafttweakerjei       | 2.0.3                    | CraftTweaker2-1.12-4.1.20.655.jar                     | None                                     |
       | L     | creativecore          | 1.10.0                   | CreativeCore_v1.10.61_mc1.12.2.jar                    | None                                     |
       | L     | creeperconfetti       | 1.4.2                    | creeperconfetti-1.4.2.jar                             | None                                     |
       | L     | cucumber              | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                             | None                                     |
       | L     | customloadingscreen   | 1.12.2-1.4.1             | CustomLoadingScreen-1.12.2-1.4.1.jar                  | None                                     |
       | L     | damagetilt            | 0.1.0                    | DamageTilt-1.12.2-0.1.0.jar                           | None                                     |
       | L     | datmoddingapi         | 1.2.1                    | datmoddingapi-1.2.1.jar                               | None                                     |
       | L     | datrandomspawn        | 1.2.1                    | datrandomspawn-1.2.1.jar                              | None                                     |
       | L     | deathquotes           | 1.2.0                    | DeathQuotes-1.2.0-mc1.12-forge.jar                    | None                                     |
       | L     | defaultoptions        | 9.2.8                    | DefaultOptions_1.12.2-9.2.8.jar                       | None                                     |
       | L     | dynamictrees          | 1.12.2-0.9.23            | DynamicTrees-1.12.2-0.9.23.jar                        | None                                     |
       | L     | dynamictreesbop       | 1.12.2-1.5.1             | DynamicTreesBOP-1.12.2-1.5.1.jar                      | None                                     |
       | L     | dynamictreesquark     | 1.12.2-1.0.6             | DynamicTreesQuark-1.12.2-1.0.6.jar                    | None                                     |
       | L     | emojiful              | 1.0.3                    | emojiful-1.0.3.jar                                    | None                                     |
       | L     | extendedcrafting      | 1.5.6                    | ExtendedCrafting-1.12.2-1.5.6.jar                     | None                                     |
       | L     | fasterladderclimbing  | 0.1-146                  | FasterLadderClimbing-1.12-0.1-146.jar                 | None                                     |
       | L     | forgelin              | 1.8.3                    | Forgelin-1.8.3.jar                                    | None                                     |
       | L     | ftbbackups            | 1.1.0.1                  | FTBBackups-1.1.0.1.jar                                | None                                     |
       | L     | ftbguides             | 2.0.0.52                 | FTBGuides-2.0.0.52.jar                                | None                                     |
       | L     | ftblib                | 5.4.7.2                  | FTBLib-5.4.7.2.jar                                    | None                                     |
       | L     | ftbutilities          | 5.4.1.131                | FTBUtilities-5.4.1.131.jar                            | None                                     |
       | L     | futureminecraf        | 1.3.1                    | FutureVersions+v1.3.1.jar                             | None                                     |
       | L     | hidenames             | 1.4.1                    | HideNames-1.12.2-1.4.1.jar                            | None                                     |
       | L     | immersivecables       | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar                      | None                                     |
       | L     | immersiveintelligence | 0.1.1                    | immersiveintelligence-1.12.2-0.1.1.jar                | None                                     |
       | L     | immersivepetroleum    | 1.1.10                   | immersivepetroleum-1.12.2-1.1.10.jar                  | None                                     |
       | L     | immersiveposts        | 0.2.1                    | ImmersivePosts-0.2.1.jar                              | None                                     |
       | L     | incontrol             | 3.9.16                   | incontrol-1.12-3.9.17.jar                             | None                                     |
       | L     | intimepresence        | 1.30                     | intimepresence-1.30.jar                               | None                                     |
       | L     | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                              | None                                     |
       | L     | itemblacklist         | 1.4.3                    | ItemBlacklist-1.4.3.jar                               | None                                     |
       | L     | jei                   | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                             | None                                     |
       | L     | jeivillagers          | 1.0                      | jeivillagers-1.12-1.0.2.jar                           | None                                     |
       | L     | jarm                  | 1.1.1                    | Just+A+Raft+Mod-1.1.1.jar                             | None                                     |
       | L     | justenoughpetroleum   | 0.1                      | JustEnoughPetroleum-0.1.jar                           | None                                     |
       | L     | jeresources           | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar               | None                                     |
       | L     | kc                    | 1.12                     | knobcontrol-1.12-4.0.20.jar                           | None                                     |
       | L     | konkrete              | 1.1.6                    | konkrete_1.1.6_MC_1.12-1.12.2.jar                     | None                                     |
       | L     | libvulpes             | 0.4.2.-83                | LibVulpes-1.12.2-0.4.2-83-universal.jar               | None                                     |
       | L     | loottweaker           | 0.3.0                    | LootTweaker-0.3.0+MC1.12.2.jar                        | None                                     |
       | L     | immersivetech         | 1.8.94                   | MCTImmersiveTechnology-1.12.2-1.8.94.jar              | None                                     |
       | L     | mcwbridges            | 1.0.6                    | mcw-bridges-1.0.6b-mc1.12.2.jar                       | None                                     |
       | L     | mtrm                  | 1.2.2.30                 | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar            | None                                     |
       | L     | testdummy             | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                            | None                                     |
       | L     | mobends               | 1.0.0-beta-20.06.20      | MoBends_1.12.2-1.0.0-beta-20.06.20.jar                | None                                     |
       | L     | modtweaker            | 4.0.19                   | modtweaker-4.0.20.4.jar                               | None                                     |
       | L     | mw                    | 0.4.6.2                  | mw_2.0-0.4.6.2_mc1.12.2.jar                           | None                                     |
       | L     | quark                 | r1.6-179                 | Quark-r1.6-179.jar                                    | None                                     |
       | L     | vanillafix            | 1.0.10-150               | VanillaFix-1.0.10-150.jar                             | None                                     |
       | L     | immersiveengineering  | 0.12-92                  | ImmersiveEngineering-0.12-92.jar                      | None                                     |
  Loaded coremods (and transformers): CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.33_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
                                        c4.colytra.asm.ElytraTransformer
                                      ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-250-universal.jar)
                                        zmaster587.advancedRocketry.asm.ClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      weaponlib (mw_2.0-0.4.6.2_mc1.12.2.jar)
                                        com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
                                      ClsPlugin (CustomLoadingScreen-1.12.2-1.4.1.jar)
                                        alexiil.mc.mod.load.coremod.ClsTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 466.11' Renderer: 'NVIDIA GeForce GTX 1650/PCIe/SSE2'
  Suspected Mods: Unknown
  Launched Version: 1.12.2-forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.11, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: VanillaTweaks_r460371.zip
  Current Language: Русский (Россия)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
