### ISSUE TITLE
crash during game

### ISSUE THREAD

**Issue by Chuunkyz** [Keksuccino/Konkrete#5]
[19:44:23] [Render thread/INFO]: [STDOUT]: ################# ERROR [KONKRETE] #################
[19:44:23] [Render thread/INFO]: [STDOUT]: Failed to invoke event!
[19:44:23] [Render thread/INFO]: [STDOUT]: Event Subscription Class: class de.keksuccino.fancymenu.menu.fancy.helper.CustomizationHelper
[19:44:23] [Render thread/INFO]: [STDOUT]: Event Subscription Method Name: onRenderPost
[19:44:23] [Render thread/INFO]: [STDOUT]: Event Name: de.keksuccino.konkrete.events.client.GuiScreenEvent$DrawScreenEvent$Post
[19:44:23] [Render thread/INFO]: [STDOUT]: ####################################################
[19:44:23] [Render thread/INFO]: [STDOUT]: 
[19:44:23] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[19:44:23] [Render thread/INFO]: [STDERR]: 	at jdk.internal.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.invokeEvent(EventHandler.java:115)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.callEventsFor(EventHandler.java:105)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.handler$fed000$onRenderPost(class_757.java:10053)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:1272)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1112)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:728)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:217)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[19:44:23] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[19:44:23] [Render thread/INFO]: [STDOUT]: ################# ERROR [KONKRETE] #################
[19:44:23] [Render thread/INFO]: [STDOUT]: Failed to invoke event!
[19:44:23] [Render thread/INFO]: [STDOUT]: Event Subscription Class: class de.keksuccino.fancymenu.menu.fancy.helper.CustomizationHelper
[19:44:23] [Render thread/INFO]: [STDOUT]: Event Subscription Method Name: onRenderPost
[19:44:23] [Render thread/INFO]: [STDOUT]: Event Name: de.keksuccino.konkrete.events.client.GuiScreenEvent$DrawScreenEvent$Post
[19:44:23] [Render thread/INFO]: [STDOUT]: ####################################################
[19:44:23] [Render thread/INFO]: [STDOUT]: 
[19:44:23] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[19:44:23] [Render thread/INFO]: [STDERR]: 	at jdk.internal.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.invokeEvent(EventHandler.java:115)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.callEventsFor(EventHandler.java:105)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.handler$fed000$onRenderPost(class_757.java:10053)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:1272)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1112)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:728)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:217)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[19:44:23] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[19:44:23] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException

and then the game freezes (can't pick blocks, mobs don't move, ...), or crashes

**Comment by Keksuccino** [comment]
This is most likely a mod incompatibility. Please try to start the game with only Konkrete installed. Then with only Konkrete + mods that depend on Konkrete and see if it works then.
